# Nouvea/Nova must be blacklisted here as well beside from the initrd to avoid a
# delayed loading (for example on Optimus laptops where the Nvidia card is not
# driving the main display).

blacklist nouveau
blacklist nova-core

# Enable complete power management. From:
# file:///usr/share/doc/nvidia-driver/html/powermanagement.html

options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_PreserveVideoMemoryAllocations=1
